// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/dice/roll.proto

package dice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RollRequest struct {
	Input                string   `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollRequest) Reset()         { *m = RollRequest{} }
func (m *RollRequest) String() string { return proto.CompactTextString(m) }
func (*RollRequest) ProtoMessage()    {}
func (*RollRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_roll_edd9f474add9e000, []int{0}
}
func (m *RollRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollRequest.Unmarshal(m, b)
}
func (m *RollRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollRequest.Marshal(b, m, deterministic)
}
func (dst *RollRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollRequest.Merge(dst, src)
}
func (m *RollRequest) XXX_Size() int {
	return xxx_messageInfo_RollRequest.Size(m)
}
func (m *RollRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RollRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RollRequest proto.InternalMessageInfo

func (m *RollRequest) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

type RollResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollResponse) Reset()         { *m = RollResponse{} }
func (m *RollResponse) String() string { return proto.CompactTextString(m) }
func (*RollResponse) ProtoMessage()    {}
func (*RollResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_roll_edd9f474add9e000, []int{1}
}
func (m *RollResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollResponse.Unmarshal(m, b)
}
func (m *RollResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollResponse.Marshal(b, m, deterministic)
}
func (dst *RollResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollResponse.Merge(dst, src)
}
func (m *RollResponse) XXX_Size() int {
	return xxx_messageInfo_RollResponse.Size(m)
}
func (m *RollResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RollResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RollResponse proto.InternalMessageInfo

func (m *RollResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*RollRequest)(nil), "api.dice.RollRequest")
	proto.RegisterType((*RollResponse)(nil), "api.dice.RollResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RollServiceClient is the client API for RollService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RollServiceClient interface {
	Roll(ctx context.Context, in *RollRequest, opts ...grpc.CallOption) (*RollResponse, error)
}

type rollServiceClient struct {
	cc *grpc.ClientConn
}

func NewRollServiceClient(cc *grpc.ClientConn) RollServiceClient {
	return &rollServiceClient{cc}
}

func (c *rollServiceClient) Roll(ctx context.Context, in *RollRequest, opts ...grpc.CallOption) (*RollResponse, error) {
	out := new(RollResponse)
	err := c.cc.Invoke(ctx, "/api.dice.RollService/Roll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RollServiceServer is the server API for RollService service.
type RollServiceServer interface {
	Roll(context.Context, *RollRequest) (*RollResponse, error)
}

func RegisterRollServiceServer(s *grpc.Server, srv RollServiceServer) {
	s.RegisterService(&_RollService_serviceDesc, srv)
}

func _RollService_Roll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollServiceServer).Roll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.dice.RollService/Roll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollServiceServer).Roll(ctx, req.(*RollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RollService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.dice.RollService",
	HandlerType: (*RollServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Roll",
			Handler:    _RollService_Roll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/dice/roll.proto",
}

func init() { proto.RegisterFile("api/dice/roll.proto", fileDescriptor_roll_edd9f474add9e000) }

var fileDescriptor_roll_edd9f474add9e000 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x2c, 0xc8, 0xd4,
	0x4f, 0xc9, 0x4c, 0x4e, 0xd5, 0x2f, 0xca, 0xcf, 0xc9, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x48, 0x2c, 0xc8, 0xd4, 0x03, 0x09, 0x2a, 0x29, 0x73, 0x71, 0x07, 0xe5, 0xe7, 0xe4, 0x04,
	0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x89, 0x70, 0xb1, 0x66, 0xe6, 0x15, 0x94, 0x96, 0x48,
	0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x38, 0x4a, 0x6a, 0x5c, 0x3c, 0x10, 0x45, 0xc5, 0x05,
	0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x62, 0x5c, 0x6c, 0x45, 0xa9, 0xc5, 0xa5, 0x39, 0x10, 0x65, 0xac,
	0x41, 0x50, 0x9e, 0x91, 0x0b, 0xc4, 0xb0, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x53,
	0x2e, 0x16, 0x10, 0x57, 0x48, 0x54, 0x0f, 0x66, 0x9d, 0x1e, 0x92, 0x5d, 0x52, 0x62, 0xe8, 0xc2,
	0x10, 0xd3, 0x9d, 0xd8, 0xa2, 0x58, 0x40, 0x82, 0x49, 0x6c, 0x60, 0xb7, 0x1a, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x10, 0xca, 0x78, 0x53, 0xc2, 0x00, 0x00, 0x00,
}
